config/routes.rb
Blog::Application.routes.draw do
  resources :users
  root :to => 'welcome#index'

  get "welcome/index"
  resources :articles do
    resources :bomments
    collection do
      get :search
    end
  end
  resources :subscribers

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :bomments,dependent: :destroy
  validate :title, presence: true,length:{minimum: 3}
  validate :title, presence: true,length:{minimum: 2}
  def self.search(params)
    articles=Article.where("body LIKE ? or title LIKE ? " "%#{params[:search]}%","%#{params[:search]}%") if params[:search].present?
    article
  end
end

app/models/bomment.rb
class Bomment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :Commenter, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :artcile
  attr_accessible :body, :commenter
end

app/models/commentnew.rb
class Commentnew < ActiveRecord::Base
  belongs_to :article
  attr_accessible :Commenter, :body
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :f_name,:l_name,:email,:country
  validates :f_name,:l_name,:email,:country,presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :userid,:password_confirmation
  #has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "Anand Verma",password: "abc123",except:[:index,:show]
  def index
    @articles=Article.all
  end


  def new
    @article=Article.new

  end
  def create
    #render plain: params[:article].inspect
    @article=Article.new(params[:article])
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
  def search
    if params[:search].blank?
      @article=Article.all
    else
      @article=Article.search(params)
    end
  end

  def edit
    @article=Article.find(params[:id])
  end
  def update
    @article=Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article
    else
      render 'edit'
    end
  end
  def show
    @article=Article.find(params[:id])
  end
  def destroy
    @article=Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
#  private
#  def article_params
#    params.require(:article).permit(:title,:text)
#  end
end

app/controllers/bomments_controller.rb
class BommentsController < ApplicationController
  http_basic_authenticate_with name: "Anand Verma",password: "abc123",except:[:create]
  def create
    @article=Article.find(params[:article_id])
    @bomment=@article.bomments.create(params[:bomment])
    redirect_to articles_path(@article)
  end

  def destroy
    @article=Article.find(params[:article_id])
    @comment=@article.bomments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article=Article.find(params[:article_id])
    @comment=@article.commentnews.create(params[:comment])
    redirect_to article_path(@article)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  http_basic_authenticate_with name: "Anand Verma",password: "abc1234",except:[:create]
  def index
     @subscribers=Subscriber.all
  end
  def create
    @subscriber=Subscriber.new(params[:subscriber])
    if Subscriber.exists?(email:@subscriber.email)
      redirect_to root_path,alert:"This email allready exists"
    elsif
      @subscriber.save
      redirect_to root_path, notice:"Thank you #{@subscriber.f_name},for subscribing to my blog"
    else
      redirect_to root_path, alert: "Sorry wrong infrmation pls try again"
    end

  end
  def destroy
    @subscriber=Subscriber.find(params[:id])
    @subscriber.destroy
    redirect_to subscribers_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def new
    @user=User.new
  end
  def create
    @user=User.new(params[:user])
    if @user.save
      redirect_to articles_path,notice: "Welcome #{@user.userid}!you  successfully created an account"

    else
      render 'new'
    end 
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bomments_helper.rb
module BommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%=form_for @article do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>
<p>
   <%= link_to 'Back',articles_path ,class:'btn btn-md btn-info'%>
  <%= link_to 'Home',welcome_index_path ,class:'btn btn-md btn-primary'%>
</p>

app/views/articles/index.html.erb
<div class='row' style='padding-top:2%;'>
<div class='col'></div>
<div class='col-md-10 '>





<h1>List of all Articles</h1>
<p>
  <%= link_to 'Create New Article', new_article_path,class:'btn btn-lg btn-info' %>
</p>
<table class='table table-hover table-striped table-responsive-xs table-danger'>
  <thead>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan='3'>Editing Options</th>
  </tr>
</thead>
  <% @articles.each do |article| %>
  <tr>
    <td>
      <%= article.title %>
    </td>
    <td>
      <%= truncate(article.text,length:65) %>
    </td>
    <td> |
      <%= link_to 'Show',article_path(article) ,class:'btn btn-sm btn-info'%>
    </td>
    <td> |
      <%= link_to 'Edit',edit_article_path(article) ,class:'btn btn-sm btn-warning'%>
    </td>
    <td> |
      <%= link_to 'Delete',article_path(article),method: :DELETE ,data:{confirm: 'Are you sure to delete?'},class:'btn btn-sm btn-danger' %>
    </td>

  </tr>
  <% end %>
</table>
<p><%= link_to 'Home',welcome_index_path ,class:'btn btn-lg btn-info'%>
</p>
</div>
<div class='col'></div>
</div>

app/views/articles/new.html.erb
<div class="row" style="padding-top:10%;">
  <div class="col"></div>
  <div class="col-md-10">


<h1>Create a New Article</h1>
<%=form_for :article, url: articles_path do |f| %>
<div class="field" style="100%">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>
<p>
  <%= f.submit class:'btn btn-lg btn-success' %>
</p>
<% end %>
<p>
   <%= link_to 'Back',articles_path,class:'btn btn-md btn-info'  %>
  <%= link_to 'Home',welcome_index_path,class:'btn btn-md btn-primary' %>
</p>
</div>
<div class="col"></div>
</div>

app/views/articles/show.html.erb
<div class='row' style='padding-top:5%;'>
<div class='col'></div>
<div class='col-md-7 '>


<p><strong>Title:</strong>
<%= @article.title %>
</p>
<p>
  <strong>Text:
  </strong>
<%= @article.text %>
</p>

<hr>
<h2>Comments</h2>
<% @article.bomments.each do |comment| %>
<p>
  <strong>Commenter:</strong>
  <%= comment.Commenter %>
</p>



<p>
  <strong>Comment</strong>
  <%= comment.body %>
</p>
<p>
<%= link_to 'Delete Comment',[comment.article,comment],method: :DELETE ,data:{confirm: 'Are you sure?'}  ,class:'btn btn-sm btn-danger' %>
</p>
<% end %>






<hr>
<h2>Add Comment<h2>
  <%= form_for([@article,@article.bomments.build]) do |f| %>
  <div class='field' style="100">
    <p>
    <%= f.label :commenter %> <br>
    <%= f.text_field :Commenter,class: 'form-control' %>
    </p>
    <p>
    <%= f.label :body %><br>
    <%= f.text_area :body,class: 'form-control' %>
    </p>
    <p>
      <%= f.submit class:'btn btn-lg btn-success'%>
    </p>
  </div>
    <% end %>

<p><%= link_to 'Back',articles_path,class:'btn btn-md btn-info' %>
 <%= link_to 'Home',welcome_index_path ,class:'btn btn-md btn-primary'%>
  </p>
</div>
  <div class='col'></div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class='show_notice'>
    <% if notice %>
    <%= notice %>
    <% end %>
  </div>
  <div class='show_alert'>
    <% if alert %>
    <%= alert %>
    <% end %>
  </div>
<%= yield %>
</div>
<%= render 'shared/footer' %>


</body>
</html>

app/views/shared/_footer.html.erb
<section class="footer">
  <div class='row'>
    <div class='col-md-4 darker'>
    <div class='col-md-12 padding white'>
    <h4>General Information</h4>
    <hr>
    <h5>Address Line 1</h5>
    <h5>Address Line 2</h5>
    <h5>Address Line 3</h5>
    <hr>
    <p class="small-font grey">&copy;anandverma.iiita@gmail.com All right Reserved</p>
   </div>
  </div>
    <div class='col-md-4'>
      <div class='col-md-12'>
      <h4>Subscribe</h4>
      <hr>
      <%= form_for :subscriber,url:subscribers_path do |f| %>
      <%= f.text_field :f_name,placeholder:"First Name",class: "form-control mr-sm-2 sm_style" %>
      <%= f.text_field :l_name,placeholder:"Last Name",class: "form-control mr-sm-2 sm_style" %>
      <%= f.email_field :email,placeholder:"your Email ID",class:"form-control mr-sm-2 sm_style" %>
      <div class="form-control">
      <%= f.select :country,options_for_select(['country1','country2','country3']),prompt:'Select your Country' %>
      </div>
      <%= f.submit 'Submit',class:"btn btn-light my-2 my-sm-0 sm_style" %>
      <% end %>
<!--      <form class='form-inline mt-2 mt-md-0'>
        <input class="form-control mr-sm-2"
        type="text"
        placeholder="Input Your Email ID" aria-label="Email" style="margin-bottom:10px; width: 100%;"><br>
        <button class="btn btn-light my-2 my-sm-0" type="submit">Submit</button>
      </form>
-->     </div>
    </div>

    <div class='col-md-4 dark'>
      <div class='col-md-12 white'>
      <h4>Social site Link</h4>
      <hr>
      <h4><%= link_to 'Facebook',welcome_index_path,class:'linktxt' %></h4>
      <h4>Linkedin</h4>
     </div>
    </div>
  </div>
</section>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">BarbieTechFabulous</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home",welcome_index_path,class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'Blog',article_path,class:"nav-link" %>
      </li>
      <li class='nav-item'>
        <a class='nav-link' href="#">About</a>

      </li>
      <li class='nav-item'>
        <%= link_to 'Create Account',new_user_path,class:'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/subscribers/index.html.erb
<div class='row' style='padding-top:15%;'>
<div class='col'></div>
<div class='col-md-10 '>





<h1>List of all Subscriber</h1>

<table class='table table-hover table-striped table-responsive-xs table-danger'>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email Address</th>
    <th>Country</th>
    <th>Delete</th>

  </tr>
</thead>
  <% @subscribers.each do |subscriber| %>
  <tr>
    <td>
      <%= subscriber.f_name %>
    </td>
    <td>
      <%= subscriber.l_name %>
    </td>
    <td>
      <%= subscriber.email %>
    </td>
    <td>
      <%= subscriber.country %>
    </td>

    <td>
      <%= link_to 'Delete',subscriber_path(subscriber),method: :DELETE ,data:{confirm: 'Are you sure to delete?'},class:'btn btn-sm btn-danger' %>
    </td>

  </tr>
  <% end %>
</table>
<p><%= link_to 'Home',welcome_index_path ,class:'btn btn-lg btn-info'%>
</p>
</div>
<div class='col'></div>
</div>

app/views/users/index.html.erb
<h1>views/users/index</h1>

app/views/users/new.html.erb
<div class="row" style="padding-top:0%;">
  <div class="col"></div>
  <div class="col-md-10">


<h1>Create an Account</h1>
<%= form_for @user do |f| %>
<div class='field' style='100%'>
<%= f.text_field :userid,placeholder:"Input user Id ",class:'form-control' %>
<%= f.email_field :email,placeholder:'Input Email Id',class:'form-control'%>
<%= f.password_field :password,placeholder:'Create Password',class:'form-control'%>


<%= f.submit 'Create Account' %>
<% end %>
</div>

<p>
   <%= link_to 'Articles',articles_path,class:'btn btn-md btn-info'  %>
  <%= link_to 'Home',welcome_index_path,class:'btn btn-md btn-primary' %>
</p>
</div>
<div class="col"></div>
</div>

app/views/welcome/index.html.erb
<div class='row' style='padding-top:15%;'>
<div class='col'></div>
<div class='col-md-7 text-center'>

<h1>Welcome To My Blog </h1>
<p><%= link_to 'My Blog WebApp',articles_path %>
</p>
</div>
<div class='col'></div>
</div>